/* poprf-ristretto-ffi: C ABI for RFC 9497 POPRF / ristretto255-SHA512 */

#ifndef POPRF_RISTRETTO_FFI_H
#define POPRF_RISTRETTO_FFI_H

/* This file is @generated by cbindgen from poprf-ristretto-ffi/src/lib.rs. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/* Forward declarations for opaque types. Layout is private to the Rust
 * implementation; consumers may only pass these pointers to functions
 * declared in this header. */
typedef struct SecretKey SecretKey;
typedef struct PublicKey PublicKey;
typedef struct BlindedElement BlindedElement;
typedef struct EvaluatedElement EvaluatedElement;
typedef struct Proof Proof;
typedef struct PoprfOutput PoprfOutput;


#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the last error message for this thread, or NULL if none.
 *
 * The returned pointer is owned by the caller and must be freed with
 * [`poprf_c_char_destroy`].
 */
char *poprf_last_error_message(void);

/**
 * Free a string returned by any `*_b64` or [`poprf_last_error_message`] call.
 *
 * # Safety
 *
 * `s` must be either NULL or a pointer previously returned by this library
 * and never yet freed. Double-free is undefined behaviour. Passing a
 * pointer obtained from a different allocator is undefined behaviour.
 */
void poprf_c_char_destroy(char *s);

/**
 * Derive a [`SecretKey`] from a 32-byte CSPRNG seed (RFC 9497 §3.2.1).
 *
 * `seed_len` MUST be exactly 32. Callers holding a longer KDF output
 * MUST extract a 32-byte slice of full entropy on their side and pass
 * it here. Returning NULL on `seed_len != 32` prevents accidental
 * silent truncation that would hide upstream contract drift.
 *
 * `info` is the application-bound key-derivation context (RFC 9497
 * §3.2.1, length-prefixed inside `DeriveKeyPair`). It MUST be smaller
 * than `2^16 - 1` bytes per RFC 9497 §5.1.
 *
 * On success, returns an owned `*mut SecretKey` that must be freed via
 * [`poprf_secret_key_destroy`]. Returns NULL on error.
 *
 * # Safety
 *
 * - `seed_ptr` must be either NULL with `seed_len == 0`, or point to
 *   `seed_len` initialised bytes.
 * - `info_ptr` must be either NULL with `info_len == 0`, or point to
 *   `info_len` initialised bytes.
 * - The library reads from both buffers but does not retain them after
 *   the call returns.
 */
SecretKey *poprf_secret_key_from_seed(const uint8_t *seed_ptr,
                                      uintptr_t seed_len,
                                      const uint8_t *info_ptr,
                                      uintptr_t info_len);

/**
 * Decode a [`SecretKey`] from its 32-byte canonical encoding (base64).
 *
 * On success, returns an owned `*mut SecretKey` that must be freed via
 * [`poprf_secret_key_destroy`]. Returns NULL on error.
 *
 * # Safety
 *
 * `s_ptr` must be either NULL with `s_len == 0`, or point to `s_len`
 * initialised bytes (the base64-encoded form, without trailing NUL).
 */
SecretKey *poprf_secret_key_decode_base64(const uint8_t *s_ptr, uintptr_t s_len);

/**
 * Encode a [`SecretKey`] as base64 of its 32-byte canonical form.
 *
 * Returns a NUL-terminated heap string the caller must free with
 * [`poprf_c_char_destroy`], or NULL on error.
 *
 * # Safety
 *
 * `sk` must be either NULL or a valid pointer returned by a constructor
 * in this library and not yet destroyed. The pointee is not modified.
 */
char *poprf_secret_key_encode_base64(const SecretKey *sk);

/**
 * Free a [`SecretKey`] returned by a constructor in this library.
 *
 * # Safety
 *
 * `sk` must be either NULL or a pointer previously returned by this
 * library and not yet destroyed. Double-free is undefined behaviour.
 */
void poprf_secret_key_destroy(SecretKey *sk);

/**
 * Derive the [`PublicKey`] corresponding to `sk`.
 *
 * On success, returns an owned `*mut PublicKey` that must be freed via
 * [`poprf_public_key_destroy`]. Returns NULL on error.
 *
 * # Safety
 *
 * `sk` must be either NULL or a valid pointer returned by a constructor
 * in this library and not yet destroyed.
 */
PublicKey *poprf_public_key_from_secret(const SecretKey *sk);

/**
 * Encode a [`PublicKey`] as base64 of its 32-byte canonical form.
 *
 * Returns a NUL-terminated heap string the caller must free with
 * [`poprf_c_char_destroy`], or NULL on error.
 *
 * # Safety
 *
 * `pk` must be either NULL or a valid pointer returned by a constructor
 * in this library and not yet destroyed.
 */
char *poprf_public_key_encode_base64(const PublicKey *pk);

/**
 * Free a [`PublicKey`] returned by a constructor in this library.
 *
 * # Safety
 *
 * `pk` must be either NULL or a pointer previously returned by this
 * library and not yet destroyed. Double-free is undefined behaviour.
 */
void poprf_public_key_destroy(PublicKey *pk);

/**
 * Decode a [`BlindedElement`] from its 32-byte canonical ristretto255
 * encoding (base64).
 *
 * On success, returns an owned `*mut BlindedElement` that must be freed via
 * [`poprf_blinded_element_destroy`]. Returns NULL on error.
 *
 * # Safety
 *
 * `s_ptr` must be either NULL with `s_len == 0`, or point to `s_len`
 * initialised bytes (the base64-encoded form, without trailing NUL).
 */
BlindedElement *poprf_blinded_element_decode_base64(const uint8_t *s_ptr, uintptr_t s_len);

/**
 * Free a [`BlindedElement`] returned by a constructor in this library.
 *
 * # Safety
 *
 * `b` must be either NULL or a pointer previously returned by this
 * library and not yet destroyed. Double-free is undefined behaviour.
 */
void poprf_blinded_element_destroy(BlindedElement *b);

/**
 * Encode an [`EvaluatedElement`] as base64 of its 32-byte canonical
 * ristretto255 encoding.
 *
 * Returns a NUL-terminated heap string the caller must free with
 * [`poprf_c_char_destroy`], or NULL on error.
 *
 * # Safety
 *
 * `e` must be either NULL or a valid pointer returned by a constructor
 * in this library and not yet destroyed.
 */
char *poprf_evaluated_element_encode_base64(const EvaluatedElement *e);

/**
 * Free an [`EvaluatedElement`] returned by a constructor in this library.
 *
 * # Safety
 *
 * `e` must be either NULL or a pointer previously returned by this
 * library and not yet destroyed. Double-free is undefined behaviour.
 */
void poprf_evaluated_element_destroy(EvaluatedElement *e);

/**
 * Encode a DLEQ [`Proof`] as base64 of its 64-byte canonical form
 * (two scalars).
 *
 * Returns a NUL-terminated heap string the caller must free with
 * [`poprf_c_char_destroy`], or NULL on error.
 *
 * # Safety
 *
 * `p` must be either NULL or a valid pointer returned by a constructor
 * in this library and not yet destroyed.
 */
char *poprf_proof_encode_base64(const Proof *p);

/**
 * Free a [`Proof`] returned by a constructor in this library.
 *
 * # Safety
 *
 * `p` must be either NULL or a pointer previously returned by this
 * library and not yet destroyed. Double-free is undefined behaviour.
 */
void poprf_proof_destroy(Proof *p);

/**
 * Server-side batched blind-evaluate (RFC 9497 §3.3.3).
 *
 * Inputs:
 * - `sk`: server secret key.
 * - `blinded_arr` / `n`: array of `n` non-NULL [`BlindedElement`] pointers.
 * - `info_ptr` / `info_len`: POPRF `info` parameter.
 * - `out_evaluated`: out-array of length `n`. Receives owned
 *   [`EvaluatedElement`] pointers on success. The caller is responsible for
 *   destroying each via [`poprf_evaluated_element_destroy`].
 * - `out_proof`: receives an owned [`Proof`] pointer on success.
 *
 * Returns 0 on success, non-zero on failure. On failure no output pointers
 * are written (caller's `out_*` slots are left untouched).
 *
 * # Safety
 *
 * - `sk` must be a valid non-NULL pointer to a `SecretKey` returned by
 *   this library.
 * - `blinded_arr` must be a valid non-NULL pointer to `n` consecutive
 *   `*const BlindedElement` pointers, each of which is a valid pointer
 *   returned by this library and not yet destroyed.
 * - `info_ptr` must be either NULL with `info_len == 0`, or point to
 *   `info_len` initialised bytes.
 * - `out_evaluated` must be a valid non-NULL pointer to `n` writable
 *   `*mut EvaluatedElement` slots, suitably aligned.
 * - `out_proof` must be a valid non-NULL pointer to one writable
 *   `*mut Proof` slot, suitably aligned.
 * - `n` must accurately describe the lengths of `blinded_arr` and
 *   `out_evaluated`.
 */
int poprf_blind_evaluate_batch(const SecretKey *sk,
                               const BlindedElement *const *blinded_arr,
                               uintptr_t n,
                               const uint8_t *info_ptr,
                               uintptr_t info_len,
                               EvaluatedElement **out_evaluated,
                               Proof **out_proof);

/**
 * Server-side offline evaluation (RFC 9497 §3.3.3 `Evaluate`).
 *
 * Returns the 64-byte POPRF output for `(input, info)` under `sk`, or NULL
 * on error. The returned [`PoprfOutput`] must be freed via
 * [`poprf_output_destroy`].
 *
 * `input` and `info` MUST each be smaller than `2^16 - 1` bytes
 * per RFC 9497 §5.1; otherwise this returns NULL.
 *
 * # Safety
 *
 * - `sk` must be either NULL or a valid pointer returned by a constructor
 *   in this library and not yet destroyed.
 * - `input_ptr` must be either NULL with `input_len == 0`, or point to
 *   `input_len` initialised bytes.
 * - `info_ptr` must be either NULL with `info_len == 0`, or point to
 *   `info_len` initialised bytes.
 */
PoprfOutput *poprf_evaluate(const SecretKey *sk,
                            const uint8_t *input_ptr,
                            uintptr_t input_len,
                            const uint8_t *info_ptr,
                            uintptr_t info_len);

/**
 * Encode a [`PoprfOutput`] as base64 of its 64-byte value.
 *
 * Returns a NUL-terminated heap string the caller must free with
 * [`poprf_c_char_destroy`], or NULL on error.
 *
 * # Safety
 *
 * `o` must be either NULL or a valid pointer returned by a constructor
 * in this library and not yet destroyed.
 */
char *poprf_output_encode_base64(const PoprfOutput *o);

/**
 * Constant-time equality of a [`PoprfOutput`] against a base64-encoded
 * expected 64-byte value.
 *
 * Returns 1 if equal, 0 if different, -1 on error (invalid base64 etc).
 *
 * # Safety
 *
 * - `o` must be either NULL or a valid pointer returned by a constructor
 *   in this library and not yet destroyed.
 * - `expected_b64_ptr` must be either NULL with `expected_b64_len == 0`,
 *   or point to `expected_b64_len` initialised bytes.
 */
int poprf_output_eq_base64(const PoprfOutput *o,
                           const uint8_t *expected_b64_ptr,
                           uintptr_t expected_b64_len);

/**
 * Free a [`PoprfOutput`] returned by a constructor in this library.
 *
 * # Safety
 *
 * `o` must be either NULL or a pointer previously returned by this
 * library and not yet destroyed. Double-free is undefined behaviour.
 */
void poprf_output_destroy(PoprfOutput *o);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* POPRF_RISTRETTO_FFI_H */
